openapi: "3.0.2"
info:
  title: Jobs
  version: "1.0"
servers:
  - url: https://digitalent.cloud/api

components:
  schemas:
    Address:
      type: object
      properties:
        "street":
          type: string
        "city":
          type: string
        "zip":
          type: string
        "province":
          type: string
        "region":
          type: string
        "state":
          type: string
        "country":
          type: string
        "geoCoordinates":
          $ref: "#/components/schemas/GeoCoordinates"
    GeoCoordinate:
      type: string
      example: "47.4708538"
      pattern: ^(-?\d+(\.\d+)?)
    GeoCoordinates:
      type: object
      properties:
        "latitude":
          $ref: "#/components/schemas/GeoCoordinate"
        "longitude":
          $ref: "#/components/schemas/GeoCoordinate"
    JobFamily:
      type: array
      maxLength: 2
      items:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
            example: "System Engineer"
    DateTime:
      type: string
      format: date-time
      example: "2022-07-12T11:47:27"
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    Employer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        address:
          type: object
          $ref: "#/components/schemas/Address"
        logo:
          type: string
          format: url
        socialMedia:
          type: object
          properties:
            [string]:
              type: string
              format: url
    Recruiter:
      properties:
        id:
          type: string
        salutation:
          type: string
        agency:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        fullName:
          type: string
        email:
          type: string
          format: email
        images:
          type: object
          properties:
            default:
              type: string
              format: url
            square:
              type: string
              format: url
            portrait:
              type: string
              format: url
    Job:
      type: object
      properties:
        id:
          type: string
        datePosted:
          $ref: "#/components/schemas/DateTime"
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
        address:
          type: object
          $ref: "#/components/schemas/Address"

paths:
  /jobs:
    get:
      responses:
        "200":
          description: Get all jobs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Job"
  /subscribe:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: "Subscription successful"
          content:
            application/json:
              schema:
                type: string
